export const metals=['Copper','Gold','Zinc','Nickel','Iron ore','Lithium'];
export const stages=['Exploration','Feasibility','Construction','Production'];
export function initialState(){return {version:1,projects:[
{id:'p1',name:'Saryarka Copper',country:'Kazakhstan',region:'Karaganda region',metal:'Copper',stage:'Feasibility',amount:8000000,type:'New equity',stake:25,summary:'A fictional copper development opportunity seeking capital for feasibility work and metallurgical testing.',use:'Complete feasibility studies and advance permitting.',owner:'Steppe Resources',documents:[{name:'Project overview',text:'DEMONSTRATION ONLY. This fictional project illustrates an investment opportunity. No reserves, licences or economic claims have been verified.'},{name:'Proposed work programme',text:'Illustrative programme: metallurgical testing, independent technical review and feasibility studies. Indicative timeline: 18 months. All information is fictional.'}]},
{id:'p2',name:'Altai Zinc Partnership',country:'Kazakhstan',region:'East Kazakhstan',metal:'Zinc',stage:'Production',amount:12000000,type:'Existing-share sale',stake:30,summary:'An illustrative shareholder sale in a fictional operating zinc business.',use:'Purchase an existing shareholder’s stake. Proceeds go to the seller.',owner:'Steppe Resources',documents:[{name:'Transaction outline',text:'DEMONSTRATION ONLY. Existing-share sale; investment proceeds would go to the selling shareholder. No actual asset is offered.'}]},
{id:'p3',name:'Talas Gold Exploration',country:'Kyrgyzstan',region:'Talas region',metal:'Gold',stage:'Exploration',amount:2500000,type:'New equity',stake:20,summary:'A fictional early-stage exploration programme for investors comfortable with geological risk.',use:'Field work and an initial drilling programme.',owner:'Steppe Resources',documents:[{name:'Exploration brief',text:'DEMONSTRATION ONLY. An illustrative exploration opportunity with no resource estimate or claim of economic viability.'}]}],requests:[],questions:[],saved:[],mandate:{metals:['Copper'],countries:['Kazakhstan'],stages:['Feasibility'],min:1000000,max:10000000}}}
export function matching(p,m){return (!m.metals.length||m.metals.includes(p.metal))&&(!m.countries.length||m.countries.some(c=>c.toLowerCase()===p.country.toLowerCase()))&&(!m.stages.length||m.stages.includes(p.stage))&&p.amount>=m.min&&p.amount<=m.max}
const clean=(v,max=200)=>String(v??'').trim().slice(0,max);
export function createProject(s,data){let p={id:crypto.randomUUID(),name:clean(data.name,100),country:clean(data.country,80),region:clean(data.region,100),metal:data.metal,stage:data.stage,amount:Number(data.amount),stake:Number(data.stake),type:data.type,summary:clean(data.summary,1500),use:clean(data.use,1000),owner:'Steppe Resources',documents:[]};if(!p.name||!p.country||!p.summary||!p.use||!metals.includes(p.metal)||!stages.includes(p.stage)||!['New equity','Existing-share sale','Combined'].includes(p.type)||!Number.isFinite(p.amount)||p.amount<=0||!Number.isFinite(p.stake)||p.stake<=0||p.stake>100)throw Error('Complete all required fields with a positive amount and a stake between 0 and 100%.');s.projects.push(p);return p}
export function requestAccess(s,id,note){if(!s.projects.some(p=>p.id===id))throw Error('Project not found.');if(s.requests.some(r=>r.projectId===id&&r.status!=='Declined'&&r.status!=='Revoked'))throw Error('An access request already exists.');if(!clean(note,1000))throw Error('Please explain your interest.');let r={id:crypto.randomUUID(),projectId:id,note:clean(note,1000),status:'Pending',investor:'Frontier Capital',date:new Date().toISOString()};s.requests.push(r);return r}
export function decide(s,id,status){let r=s.requests.find(r=>r.id===id);if(!r||!['Approved','Declined','Revoked'].includes(status))throw Error('Invalid request or decision.');if(status==='Revoked'&&r.status!=='Approved')throw Error('Only approved access can be revoked.');if(status!=='Revoked'&&r.status!=='Pending')throw Error('This request is no longer pending.');r.status=status;return r}
export function canAccess(s,id,role){return role==='owner'||s.requests.some(r=>r.projectId===id&&r.status==='Approved')}
export function addQuestion(s,id,role,text){if(!s.projects.some(p=>p.id===id)||!canAccess(s,id,role))throw Error('Approved access is required.');if(!clean(text,2000))throw Error('Write a message first.');let q={id:crypto.randomUUID(),projectId:id,author:role==='owner'?'Steppe Resources':'Frontier Capital',text:clean(text,2000),date:new Date().toISOString()};s.questions.push(q);return q}
